title: [Portfolio]
description: [Object-Oriented Programming Portfolio]
author:Test student.
remote_theme: pages-themes/merlot@v0.2.0

Show_downloads: true

github:
  is_prject_page: true
  
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

includes:
- images
